### PR TITLE
Add tests to config

### PR DESCRIPTION
**Pull request by banphlet**
#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch of Parrafin.
- [x] Branch name is descriptive. 
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Checklist:
- [x] All test are passing. 
- [x] Tested changes locally.
- [x] Api Documentation follows api standards.
- [x] Improved documentation or readme where necessary. 
- [x] Your commits messages format follows our commit message guideline.

#### What does this pr do?
This PR addes testes to config components

### CODE REVIEW

**Comment by expandboard** [comment]
## Thanks for your nice PR

- [x] in cloud/main.js it seems that const Parse = require('parse') must be deleted.

**Comment by banphlet** [comment]
@expandboard though parse is global variable, `standard` would throw an error `parse is not defined`

**Comment by banphlet** [comment]
> @banphlet cloud folder path is defined in index.js and it seems does not need to define Parse again in cloud/main.js according [parseserver-example](https://github.com/parse-community/parse-server-example) . parseserver use a router to find this file when defined in Parse Settings in index.js
> it throw error when add Parse const. npm start is working for you?
> 
> ```
> optional dependency [kerberos] found but version [1.0.0] did not satisfy constraint [>= 0.0.23 < 1.0.0]
> C:\Users\dashtestan\Documents\Nodetest\apiserver\cloud\main.js:7
> Parse.Cloud.define('hello', async (request) => {
>             ^
> 
> TypeError: Parse.Cloud.define is not a function
>     at Object.<anonymous> (C:\Users\dashtestan\Documents\Nodetest\apiserver\cloud\main.js:7:13)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at new ParseServer (C:\Users\dashtestan\Documents\Nodetest\apiserver\node_modules\parse-server\lib\ParseServer.js:162:9)
>     at new _ParseServer (C:\Users\dashtestan\Documents\Nodetest\apiserver\node_modules\parse-server\lib\index.js:54:18)
> ```
> when i remove this line it works
> 
> `const Parse = require('parse')`

ok @expandboard i would remove and exclude parse from standard

**Comment by expandboard** [comment]
Thanks Nana. i merge it.

**Pull request merged**
